os: linux
language: php
php:
  - 7.4
  
branches:
  only:
    - master

install:
  - curl -sSOL https://cecil.app/cecil.phar && php cecil.phar --version

script:
  - php cecil.phar new:site
  - php cecil.phar build -v

deploy:
  provider: pages
  edge: true
  token: $GH_TOKEN
  local_dir: _site
  on:
    branch: master
