os: linux
language: php
php:
  - 8.1
  
branches:
  only:
    - master

# download Cecil
install:
  - curl -sSOL https://cecil.app/cecil.phar
  - php cecil.phar --version

# create and build a new website without interaction
script:
  - php cecil.phar new:site --no-interaction
  - php cecil.phar build --verbose

# deploy to GitHub Pages
deploy:
  provider: pages
  edge: true
  token: $GH_TOKEN
  local_dir: _site
  on:
    branch: master
