name: Build and deploy to GitHub Pages
on:
  push:
    branches: [main, master]
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Cecil
        run: |
          curl -sSOL https://cecil.app/cecil.phar
      - name: Create a new site
        run: |
          php cecil.phar new:site --demo --force --no-interaction
      - name: Build site
        uses: Cecilapp/Cecil-Action@v4
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
