name: Build and deploy to GitHub Pages
on:
  push:
    branches: [main, master]
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: pre-installed
          extensions: mbstring, fileinfo, gd, imagick, intl, gettext, :redis
      - name: Download Cecil
        run: |
          curl -sSOL https://cecil.app/cecil.phar
      - name: Create a new site
        run: |
          php cecil.phar new:site --demo --force --no-interaction
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Building site with Cecil
        shell: bash
        run: |
          php cecil.phar build -v --baseurl="${{ steps.pages.outputs.base_url }}/"
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
