name: Build & deploy website

on:
  push:
    branches: [main, master]
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Cecil
        run: |
          curl -sSOL https://cecil.app/cecil.phar
          php cecil.phar --version
      - name: Create a new site
        run: |
          php cecil.phar new:site --force --no-interaction
      - name: Build with Cecil
        run: |
          php cecil.phar build --verbose
        env:
          CECIL_BASEURL: https://cecilapp.github.io/skeleton/
          CECIL_CANONICALURL: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
